config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  get '/about', to: 'pages#about'

  get '/contact_us', to: 'pages#contact_us'

  root 'posts#index'
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user

    validates :comment, length: { minimum: 5 }
end

app/models/post.rb
class Post < ApplicationRecord
    has_attached_file :image, styles: {large: "600x600", medium: "300x300", thumb: "150x150"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    validates :title, length: { minimum: 5 }
    validates :body, length: { minimum: 50 }
    validates :image, presence: true

    has_many :comments
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments

  attr_writer :login

  def login
    @login || self.username || self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:commentor, :comment))
		@comment.user_id = current_user.id
		@comment.save

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def index
        @posts = Post.all.order('created_at DESC')
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end 

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to root_path
    end

    private

    def post_params
        params.require(:post).permit(:title,:body,:image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment_clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= User.find(comment.user_id).username %></strong></p>
		<p class="comment_body"><%= comment.comment %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<% if user_signed_in? && current_user.id == comment.user_id %>
	<p><%= link_to 'Delete', [comment.post, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
 	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.text_area :comment %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hbblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class= 'nav_bar'>
    <%= link_to root_path do %>
      <h1>Welcome to Adventure</h1>
    <% end %>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact Us', contact_us_path %></li>
      </ul>
  </div>
        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div id= 'about_page'>
    <div id="about_image_container">
        <img src="/assets/about.jpg">
    </div>

    <div id='about_text'>
     <h1>Our Beginning</h1>

     <p>Nam faucibus ligula pharetra dolor finibus, nec porttitor ex condimentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean nec nunc nibh. Suspendisse sem ex, pellentesque ac bibendum eget, pellentesque rhoncus quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed tristique lorem at nunc finibus hendrerit. Sed placerat, diam sit amet porta tempor, quam est pulvinar ipsum, at sagittis massa leo ut sem. Nullam a euismod erat, id egestas sem. Maecenas id magna velit. Sed non tristique risus. Pellentesque tincidunt, dolor at interdum dapibus, purus tellus placerat nunc, non aliquam lorem ligula et est.

     Vestibulum porttitor eros in quam efficitur, a porta sapien rutrum. Nam facilisis diam diam, quis venenatis diam eleifend id. Maecenas facilisis interdum ipsum eget aliquam. Quisque urna sem, ornare at laoreet at, venenatis id libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam et nisi sed tellus imperdiet pellentesque. Proin tincidunt metus sapien, vel consectetur est tempus at. In elementum pretium erat id condimentum. Praesent et nibh ac mauris ullamcorper blandit a ac nunc. Praesent at massa maximus, sodales purus vitae, dictum ex. Nullam pulvinar varius nisl id vestibulum. Sed ornare sodales elit, eget facilisis libero tristique id. Quisque eu suscipit leo, quis volutpat erat.</p>
    </div>

</div>

app/views/pages/contact_us.html.erb
<div id='contact_us'>
    <dl>
        <dt>Email</dt>
        <dd>welcome@gmail.com</dd>
        <dt>Phone</dt>
        <dd>234-234-2344</dd>
        <dt>Facebook</dt>
        <dd>facebook.com/welcome</dd>
        <dt>Instagram</dt>
        <dd>instagram.com/welcome</dd>
    </dl>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |form| %>

  <% if @post.errors.any? %>
    <h3><%= pluralize(@post.errors.count, 'error') %> prevented this post froms saving:</h3>
      <ul>
        <% @post.errors.full_messages.each do |msg|%>
          <li><%=msg%></li>
        <% end %>
      </ul>
  <% end %>
  <p>
    <%= form.text_field :title, placeholder: 'Title' %>
  </p>
 
  <p>
    <%= form.text_area :body, placeholder: 'Body' %>
  </p>

  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div class= 'new_wrapper'>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class='page_wrapper'>
    <div class='side_bar'>
        <img src="assets/logo.jpg" id= "logo">
        <p id= 'blurb'>Cras eu commodo purus. Donec finibus ligula a vestibulum eleifend. Donec luctus nulla et erat efficitur sollicitudin. Sed consectetur consequat Nullam tempor dolor gravida laoreet fermentum.
        </p>

        <% if user_signed_in? && current_user.admin? %>
            <p id='admin_btn'><%= link_to 'New Post', new_post_path %>
            <p id='admin_btn'><%= link_to 'Logout', destroy_user_session_path, method: :delete %></p>
        <% else %>
            <% if user_signed_in? %>
                <p id='admin_btn'><%= link_to 'Logout', destroy_user_session_path, method: :delete %></p>
            <% else %>
                <p id='admin_btn'><%= link_to 'Login', new_user_session_path %></p>
            <% end %>
        <% end %>
    </div>

    <div class='posts'>
        <% @posts.each do |post| %>
            <%= link_to post_path(post) do%>
            <div class='post_wrapper'>
                <div id= "post_image">
                    <%= image_tag post.image.url(:medium) %>
                </div>
                <div id="post_text">
                    <h1><%= post.title %></h1>
                    <p><%= post.body %></p>
                </div>    
            </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<div class= 'show_page'>
    <%= image_tag @post.image.url(:large) %><br>
    <div id='text_wrapper'>
        <strong><%= @post.title %></strong><br>
        <p><%= @post.body %></p><br>
        <% if current_user.admin? %>
            <%= link_to 'edit', edit_post_path(@post) %><br>
            <%= link_to 'delete', post_path(@post), method: :delete %><br>
            <%= link_to "back", root_path %>
        <% else %>
            <%= link_to "back", root_path %>
        <% end %>
        <div id="comments">
            <h2><%= @post.comments.count %> Comments</h2>
            <%= render @post.comments %>

            <h3>Add a comment:</h3>
            <%= render "comments/form" %>
        </div>
    </div>
</div>